name: Sync Docs to Wiki

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the GITHUB_TOKEN has write permissions

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Checkout Wiki repository
        run: |
          git clone https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.wiki.git wiki-repo

      - name: Sync files
        run: |
          rm -rf wiki-repo/*
          cp -r docs/* wiki-repo/
          cd wiki-repo
          git add .
          git commit -m "Sync docs to wiki on $(date +'%Y-%m-%d %H:%M:%S')" -a || echo "No changes to commit"
          git push