name: Sync Docs to Wiki

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'

jobs:
  sync-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.email "your-email@example.com" # Replace with your email
          git config --global user.name "Your Name" # Replace with your name

      - name: Deploy SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.WIKI_DEPLOY_KEY }}

      - name: Checkout Wiki repository
        run: |
          git clone git@github.com:${{ github.repository }}.wiki.git wiki-repo

      - name: Sync files
        run: |
          echo "Syncing files from docs/ to wiki-repo/"
          rm -rf wiki-repo/*
          cp -r docs/* wiki-repo/
          cd wiki-repo
          git add .
          git commit -m "Sync docs to wiki on $(date +'%Y-%m-%d %H:%M:%S')" -a || echo "No changes to commit"
          git push